"""Modelos Pydantic del cliente datos-mexico."""

from datos_mexico.models.base import (
    ApiResponse,
    DatosMexicoModel,
    HealthResponse,
    PaginatedResponse,
)
from datos_mexico.models.cdmx import (
    BrechaEdadRow,
    BrutoNetoBucket,
    CatalogItem,
    DashboardStats,
    DistribucionSueldoBucket,
    DistributionItem,
    GenderGapSectorRow,
    LabeledAvg,
    LabeledAvgCount,
    PuestoRanking,
    Sector,
    SectorAggregate,
    SectoresComparison,
    SectorRanking,
    SectorStats,
    Servidor,
    ServidoresStats,
    TopPosition,
    TopPuesto,
)

__all__ = [
    "ApiResponse",
    "BrechaEdadRow",
    "BrutoNetoBucket",
    "CatalogItem",
    "DashboardStats",
    "DatosMexicoModel",
    "DistribucionSueldoBucket",
    "DistributionItem",
    "GenderGapSectorRow",
    "HealthResponse",
    "LabeledAvg",
    "LabeledAvgCount",
    "PaginatedResponse",
    "PuestoRanking",
    "Sector",
    "SectorAggregate",
    "SectorRanking",
    "SectorStats",
    "SectoresComparison",
    "Servidor",
    "ServidoresStats",
    "TopPosition",
    "TopPuesto",
]
